# Starting template only

name: Auto-add open issues to WhyDRS Project

on:
  issues:
    types: [opened, edited]

jobs:
  add-to-project:
    runs-on: ubuntu-latest

    steps:
      - name: Add issue to WhyDRS Project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PROJECT_ID="PVT_kwDOBCaxNM4AZRMj"  # Replace with your actual project ID
          ISSUE_ID="${{ github.event.issue.node_id }}"
          
          curl -X POST -H "Authorization: bearer $GITHUB_TOKEN" \
            -d '{"query": "mutation { addProjectNextItem(input: {projectId: \"'"$PROJECT_ID"'\", contentId: \"'"$ISSUE_ID"'\" }) { projectNextItem { id } } }"}' \
            https://api.github.com/graphql
